apiVersion: v1
kind: ConfigMap
metadata:
  name: nadsoft-config
  namespace: nadsoft
data:
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "student_db"
  DB_USER: "nadsoft_user"
  NODE_ENV: "production"
  MYSQL_DATABASE: "student_db"
  MYSQL_USER: "nadsoft_user"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: nadsoft
data:
  init.sql: |
    -- Create database if not exists
    CREATE DATABASE IF NOT EXISTS student_db;
    USE student_db;

    -- Create students table
    CREATE TABLE IF NOT EXISTS students (
      id INT AUTO_INCREMENT PRIMARY KEY,
      first_name VARCHAR(255) NOT NULL,
      last_name VARCHAR(255) NOT NULL,
      email VARCHAR(255) UNIQUE NOT NULL,
      dob DATE,
      gender ENUM('Male', 'Female', 'Other'),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    -- Create subjects table
    CREATE TABLE IF NOT EXISTS subjects (
      subject_id INT AUTO_INCREMENT PRIMARY KEY,
      subject_name VARCHAR(255) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Create marks table
    CREATE TABLE IF NOT EXISTS marks (
      id INT AUTO_INCREMENT PRIMARY KEY,
      student_id INT,
      subject_id INT,
      marks_obtained INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
      FOREIGN KEY (subject_id) REFERENCES subjects(subject_id) ON DELETE CASCADE
    );

    -- Insert sample subjects
    INSERT IGNORE INTO subjects (subject_name) VALUES
    ('Mathematics'),
    ('Physics'),
    ('Chemistry'),
    ('Biology'),
    ('English');

    -- Insert sample student (optional)
    INSERT IGNORE INTO students (first_name, last_name, email, dob, gender) VALUES
    ('Ram', 'Mishra', 'ram@gmail.com', '2000-01-15', 'Male');